name: "Almond AI Theme"
author: "Almond AI"
version: "1.0.0"
baseurl: "/almondai-website" # Replace 'repository-name' with your GitHub Pages repository name
layout:
  theme_color: "#a0522d" # Earthy almond orangey-brown
  background_color: "#faf3e0" # Light almond shell color
  text_color: "#333333" # Dark text color for readability
  link_color: "#d2691e" # Orangey-brown link color
  fonts:
    primary: "'Roboto', sans-serif"

navigation:
  - title: "Home"
    url: "/"
  - title: "About Us"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Products"
    url: "/products/"

header:
  logo: "assets/images/logo.webp"
  title: "Almond AI"

footer:
  social:
    - title: "LinkedIn"
      url: "https://linkedin.com/company/almond-ai"
    - title: "GitHub"
      url: "https://github.com/daanyaal1"
  copyright: "&copy; 2024 Almond AI. All rights reserved."
